apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.ORG}}/{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: nuxeo-nightly-server
      context: server
      kaniko:
        dockerfile: Dockerfile
        buildContext:
          localDir: {}
        buildArgs:
          BUILDER_IMAGE: ${DOCKER_REGISTRY}/${ORG}/builder-cloud:${VERSION}
          BASE_IMAGE: ${DOCKER_REGISTRY}/${ORG}/base-cloud:${VERSION}
          NUXEO_PLATFORM_VERSION: ${NUXEO_PLATFORM_VERSION}
        cache:
          repo: ${DOCKER_REGISTRY}/${ORG}/cloud/cache
    - image: nuxeo-nightly-ui
      context: ui
      kaniko:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: ${DOCKER_REGISTRY}
          NUXEO_PACKAGES: ${NUXEO_PACKAGES}
          NUXEO_WEBUI_VERSION: ${NUXEO_WEBUI_VERSION}
        buildContext:
          localDir: {}
        cache:
          repo: ${DOCKER_REGISTRY}/${ORG}/nuxeo-nightly-ui/cache
  cluster:
    namespace: webui

