apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: preview
spec:
  template:
    metadata:
      labels:
        app: preview
    spec:
      containers:
      - name: preview
        image: "{{ .Values.nuxeo.webui.image.repository }}:{{ .Values.nuxeo.webui.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
